project:
  type: book

book:
  title: "Reflex Testing using Machine Learning in the Clinical Laboratory"
  author: "Kyle Belanger"
  date: "8/2/2022"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - references.qmd


bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: journal
  docx:
    reference-doc: extras/custom-reference.docx
    number-sections: false


editor: visual

exectue:
  freeze: auto

