project:
  type: book

book:
  title: "Reflex Testing using Machine Learning in the Clinical Laboratory"
  author: "Kyle Belanger"
  date: "8/2/2022"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - references.qmd
  abstract: "This is a test to see what happens with this"



bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: journal
    default-image-extension: png
  docx:
    reference-doc: extras/custom-reference.docx
    number-sections: true
    number-depth: 1
    default-image-extension: emf




editor: visual


