project:
  type: book

book:
  title: "DHSC-Capstone"
  author: "Kyle Belanger"
  date: "8/2/2022"
  chapters:
    - index.qmd
    - chapter2.qmd
    - references.qmd
  appendices:
    - appendices/survey.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: journal
  docx:
    reference-doc: extras/custom-reference.docx


editor: visual

