# Introduction

The early 20th century marked the beginning of a quality movement in
hospitals and laboratories that began with physicians and healthcare
workers. In the early part of the century, many hospitals started
reorganizing their laboratories to be headed by biochemists.
Professional organizations emerged as self-regulating groups that helped
ensure the skills and knowledge of laboratory professionals would pass
the scrutiny of the hospitals that employed them [@berger1999]. An
American Medical Association survey later showed that 48% of U.S.
hospitals had clinical laboratories by 1923 [@berger1999]. Before 1960,
almost all testing in the laboratory was performed using manual methods.
In the mid-1960s, a limited amount of automated analyzers became
available, allowing for more rapid testing and running multiple tests at
the same time [@park2017]. Since these early days of automation in the
last fifty years, the clinical laboratory has rapidly expanded
automation techniques. These include pre-packaged ready-to-use reagents,
automated dispensing, incubation and measurement, automated sample
processing (e.g., total laboratory automation systems, one- and
two-dimensional bar codes, radio frequency identification tags),
multiplexing tests from a single sample (e.g., microarrays), automated
data processing (e.g., reference range, alert value comparisons, quality
control assessment), automated interpretation (e.g., auto-verification),
image analysis (e.g., automated peripheral blood smear morphology -
CellaVision, whole slide scanning in surgical pathology), and mobile or
static robots to operate analyzers [@park2017]. This rise in automation
in the clinical laboratory has also led to the need for more advanced
computer systems to go along with the advances in instrument technology.
Over the past few decades, LISs have evolved from relatively narrow,
often arcane, or home-grown systems into sophisticated systems that are
more user-friendly and support a broader range of functions and
integration with other technologies that laboratories deploy
[@henricks2015]. Modern LISs consist of complex, interrelated computer
programs and infrastructure that support laboratories' vast array of
information-processing needs. LISs have functions in all phases of
patient testing, including specimen and test order intake, specimen
processing and tracking, support of analysis and interpretation, and
report creation and distribution. In addition, LISs provide management
reports and other data that laboratories need to run their operations
and to support continuous improvement and quality initiatives
[@henricks2015].

The clinical laboratory's primary business purpose is to provide testing
results requested by physicians and other healthcare professionals. In a
broad sense, this testing is used to help solve diagnostic problems
[@verboeket-vandevenne2012]. To continue adding value to the
laboratory's business purpose, laboratory professionals can add value
beyond just running the provided tests. Laboratory professionals can add
value through both reflective and reflex testing. Automated analyzers
add most tests based on rules (algorithms) established by laboratory
professionals; this is defined as 'reflex testing.' Clinical biochemists
add the remainder of tests after considering a more comprehensive range
of information that can readily be incorporated into reflex testing
algorithms; this is defined as 'reflective testing' [@srivastava2010].
Both reflex and reflective testing became possible with the advent of
laboratory information systems (LIS) that were sufficiently flexible to
permit modification of existing test requests at various stages of the
analytical process [@srivastava2010]. This research study will focus
specifically on reflex testing, those tests added automatically by a set
of rules established in each laboratory. In most current clinical
laboratories, reflex testing is performed with a 'hard' cutoff, using a
specifically established range with no means of flexibility
[@murphy2021]. This study will examine the use of Machine learning to
develop algorithms to allow flexibility for automatic reflex testing in
clinical chemistry. The goal is to fill the gap between hard-coded
reflex testing and fully manual reflective testing using machine
learning algorithms.

## Purpose and Research Statement

Develop and test a machine learning algorithm to establish if said
algorithm can perform better then current hard coded rules to reduced
unnecessary patient testing.

## Significance

Health spending in the U.S. increased by 4.6% in 2019 to \$3.8 trillion
or \$11,582 per capita. This growth rate is in line with 2018 (4.7
percent) and slightly faster than what was observed in 2017 (4.3
percent) [@americanmedicalassociation2021]. Although laboratory costs
comprise only about 5% of the healthcare budget in the United States, it
is estimated that laboratory services drive up to 70% of all downstream
medical decisions, which encompass a substantial portion of the budget
[@ma2019]. As healthcare budgets increase, payers, including Medicare,
commercial insurers, and employers, will demand accountability and
eliminate the abuse and misuse of ineffective testing strategies
[@hernandez2003]. Increasingly, payers demand to know the value of the
tests, with value equaling quality per unit of cost. Payers want
laboratories to prove that tests are cost-effective; as reimbursement
rates decline for many standard laboratory tests, the incentives for
automated reflex testing rise for many clinical laboratories
[@hernandez2003]. Unnecessary laboratory tests are a significant source
of waste in the United States healthcare system. Prior studies suggest
that 20% of labs performed are unnecessary, wasting 200 billion dollars
annually [@li2022].

A typical example of reflex testing is thyrotropin (TSH), relaxing to
free thyroxine (Free T4 or FT4). TSH measurement is a sensitive
screening test for thyroid dysfunction. Guidelines from the American
Thyroid Association, the American Association of Clinical
Endocrinologists, and the National Academy of Clinical Biochemistry have
endorsed TSH measurement as the best first-line strategy for detecting
thyroid dysfunction in most clinical settings [@plebani2020].
Traditionally the cutoff for reflex testing was simply the reference
range for a patient's sex and race. However, recent studies have
suggested that widening these ranges reduces reflex testing by up to 34%
[@plebani2020]. In an additional study, the authors concluded that the
TSH reference range leading to reflex Free T4 testing could likely be
widened to decrease the number of unnecessary Free T4 measurements
performed. This reduction would reduce overall costs to the medical
system without likely causing negative consequences of missing the
detection of people with thyroid hormone abnormalities
[@woodmansee2018]. Even with the potential reduction in testing, the
hard-coded reflex rule still exists.
